In [71]:
# numpy should be installed
# pip install numpy
import numpy as np
# Our aim is implementing Gaussion elimination with Scaled row pivoting.
# Given A, find P, L, U st P*A = L*U

# Finds next pivot from remaining lines
def find_next_pivot(A, pos_pivots):
    max_scale = 1e-7
    res_pivot = -1
    
    for pivot in pos_pivots:
        row_max = np.max(np.abs(A[pivot]))
        scale = np.abs(A[pivot, A.shape[0]-len(pos_pivots)]) / row_max

        if scale > max_scale:
            max_scale = scale
            res_pivot = pivot
            
    return res_pivot

'''
A = np.array([
    [-2, 5, 2],
    [-1., 2, 4],
    [3, 1, 1]
])
'''

'''

eps = 1e-8

A = np.array([
    [eps, 1],
    [1, 1],
])
'''

# create random 4*4 matrix
A = np.random.rand(4, 4)

n = A.shape[0]

# Firstly, all of the rows are candidates for being pivot
pos_pivots = []
for i in range(A.shape[0]):
    pos_pivots.append(i)
    
P = np.zeros((n, n))
L = np.eye(n)
U = np.copy(A)

non_invertible = False


# Gaussion elimination without considering lower and upper triangulity, it will be done below
order_of_rows = []
for i in range(0, n):
    
    pivot = find_next_pivot(U, pos_pivots)
    
    if -1 == pivot:
        non_invertible = True
        break
    
    order_of_rows.append(pivot)
    pos_pivots.remove(pivot)
    
    Li = np.eye(n)
    
    for j in pos_pivots:
        
        scale = -U[j, i]/U[pivot, i]
        Li[j, pivot] = -scale
        U[j] += scale*U[pivot]
        
    L = L.dot(Li)
    
if non_invertible:
    print ("This matrix is non invertible, So PLU decomposition cannot be found")
else:
    
    # calculate P and order L and U
    # supply lower and upper triangulity
    
    U[range(0, n)] = U[order_of_rows]
    L[range(0, n)] = L[order_of_rows]
    
    for i in range(0, n):
        L[i, range(0, n)] = L[i, order_of_rows]
    
    for i in range(0, n):
        P[i, order_of_rows[i]] = 1
        
    PA = P.dot(A)
    LU = L.dot(U)
        
    print("P = ", P)
    print("")
    print("L = ", L)
    print("U = ", U)
    
    # Control if PA=LU or not
    comparison = True
    for i in range(0, n):
        for j in range(0, n):
            if abs(PA[i,j]-LU[i,j]) > 1e-5:
                comparison = False
    assert(comparison)
    
    
    
    
    

P =  [[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]

L =  [[ 1.          0.          0.          0.        ]
 [ 1.12402511  1.          0.          0.        ]
 [ 0.97011087 -0.12956421  1.          0.        ]
 [ 0.64168388  0.7281897   0.26113027  1.        ]]
U =  [[ 7.69607936e-01  3.56710788e-01  1.59630144e-01  6.68491551e-01]
 [-1.11022302e-16  5.98710242e-01 -1.58191944e-01  2.06713078e-01]
 [-1.43845171e-17  0.00000000e+00  6.95177229e-01  2.34855151e-01]
 [ 8.46015303e-17  0.00000000e+00  0.00000000e+00  1.08323983e-01]]
